name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Install pytest
        run: docker-compose exec pythonapp pip install pytest

      - name: Build and run tests
        run: |
          docker-compose exec -T pythonapp python -m pytest
        env:
          DATABASE_HOST: localhost
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DATABASE_NAME: db
