name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
        ports:
          - "3308:3306"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name : Stoping Dockers
        run : docker-compose stop

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose exec -T pythonapp pip install -r requirements.txt

      - name: Run tests
        run : ls

    env:
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: db
